name: Test CI
on:
  push:
    paths:
      - '**.ring'
      - '**.dll'
      - '**.so'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Run tests
        uses: ysdragon/ring-action@v1.0.6
        with:
          file: "tests/TOML_test.ring"